# -------------------------------
# 1. Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-backend
  namespace: platform
  labels:
    app: crypto-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: crypto-backend
    spec:
      restartPolicy: Always
      containers:
        - name: crypto-backend
          image: frozenwolf2003/crypto-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: platform-secrets

          command: ["/bin/sh", "-c"]
          args:
            - |
              exec uvicorn main:app --host 0.0.0.0 --port 8000 --workers 0

          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 90
            failureThreshold: 1

          volumeMounts:
            - name: backend-pvc
              mountPath: app/data
      volumes:
        - name: backend-pvc
          persistentVolumeClaim:
            claimName: backend-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/backend-data   # make sure this folder exists on VM
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: backend-pv
  storageClassName: ""   # ← this is required

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-backend-ingress
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/whitelist-source-range: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - crypto-backend.gokuladethya.uk
      secretName: crypto-backend-tls
  rules:
    - host: crypto-backend.gokuladethya.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crypto-backend
                port:
                  number: 8000
