# -------------------------------
# 1. Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-backend
  namespace: platform
  labels:
    app: crypto-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: crypto-backend
    spec:
      restartPolicy: Always
      containers:
        - name: crypto-backend
          image: frozenwolf2003/crypto-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: platform-secrets

          command: ["/bin/sh", "-c"]
          args:
            - |
              exec uvicorn main:app --host 0.0.0.0 --port 8000 --workers 0

          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 90
            failureThreshold: 1

          volumeMounts:
            - name: custom
              mountPath: backend-pvc
      volumes:
        - name: backend-pvc
          persistentVolumeClaim:
            claimName: backend-pvc

---
# PersistentVolumeClaim for shared storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: backend-pvc
  storageClassName: ""   # ← this is required

---
# PersistentVolumeClaim for shared storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: shared-pv
  storageClassName: ""   # ← this is required