apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true

    [grafana_net]
    url = https://grafana.net

    [log]
    mode = console

    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    domain = grafana.gokuladethya.uk

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    hide_version = true
    device_limit = 100

    [feature_toggles]
    enable = displayAnonymousStats
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.1.1
    helm.sh/chart: grafana-9.4.4
  name: prometheus-grafana
  namespace: prometheus
