apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: python:3.11-slim
          command: ["bash", "-c"]
          args:
            - |
              echo "checking env variables"
              echo $MLFLOW_DB
              echo $AWS_ACCESS_KEY_ID
              echo $AWS_SECRET_ACCESS_KEY
              echo $S3_URL
              echo "Starting MLflow server..."
              pip install --no-cache-dir mlflow[auth] psycopg2-binary boto3 gunicorn &&
              mlflow server \
                --backend-store-uri $MLFLOW_DB \
                --default-artifact-root s3://mlops/ml-flow \
                --host 0.0.0.0 \
                --port 5000 \
                --app-name basic-auth  --gunicorn-opts "--workers 1"

              
          ports:
            - containerPort: 5000
          # livenessProbe:
          #   httpGet:
          #     path: /api/2.0/mlflow/experiments/list
          #     port: 5000
          #   initialDelaySeconds: 300
          #   periodSeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /api/2.0/mlflow/experiments/list
          #     port: 5000
          #   initialDelaySeconds: 300
          #   periodSeconds: 10
          env:
            - name: MLFLOW_FLASK_SERVER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MLFLOW_FLASK_SERVER_SECRET_KEY
            - name: MLFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: MLFLOW_DB
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "auto"
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: S3_URL
          volumeMounts:
            - name: shared
              mountPath: /mlflow
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: platform
spec:
  type: NodePort 
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050

