executor: KubernetesExecutor

env:
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: /opt/airflow/dags/
  - name: PYTHONPATH
    value: /opt/airflow
  - name: TEST_ENV
    value: "GOKULADETHYA"
  - name: AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE
    value: /opt/airflow/pod_templates/pod_template_file.yaml

volumeMounts:
  - name: airflow-dags
    mountPath: /opt/airflow/custom_persistent_shared
volumes:
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: shared-pvc

extraVolumes:
  - name: pod-template
    configMap:
      name: airflow-pod-template
extraVolumeMounts:
  - name: pod-template
    mountPath: /opt/airflow/
    readOnly: true

extraEnv: |
  - name: KAFKA_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: MLFLOW_TRACKING_URI
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_URI
  - name: MLFLOW_TRACKING_USERNAME
    value: "admin"
  - name: MLFLOW_TRACKING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_ADMIN_PASSWORD

extraEnvFrom: |
  - secretRef:
      name: platform-secrets

securityContext:
  runAsUser: 0        # UID you want Airflow to run as
  runAsGroup: 0
  fsGroup: 0          # ensures shared volumes are accessible


webserverSecretKeySecretName: my-webserver-secret
# Use your custom image everywhere
airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest

  config:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/
    AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /opt/airflow/pod_templates/pod_template_file.yaml
  env:
    - name: PYTHONPATH
      value: /opt/airflow



# Ensure DAG processor, scheduler, triggerer all use your image
# DAGs
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    wait: 10
  persistence:
    enabled: true
    existingClaim: shared-pvc-airflow
    accessMode: ReadWriteMany

flower:
  enabled: false

# logs:
#   persistence:
#     enabled: true

redis: 
  enabled: false

metrics:
  enabled: true
  statsd:
    enabled: true
    host: airflow-statsd
    port: 9125
    prefix: airflow
