executor: CeleryExecutor  # or KubernetesExecutor

# Airflow main image and env
airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest
  config:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/repo/dags/
  env:
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo

# DAGs configuration
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    wait: 10
    # Mount path must match AIRFLOW__CORE__DAGS_FOLDER minus the 'dags' subfolder
    root: /opt/airflow/dags/repo
    dest: dags
  persistence:
    enabled: true
    existingClaim: shared-pvc-airflow  # must be RWX
    accessMode: ReadWriteMany
    mountPath: /opt/airflow/dags/repo

# Extra environment variables (shared by all pods)
extraEnv: |
  - name: KAFKA_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: MLFLOW_TRACKING_URI
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_URI
  - name: MLFLOW_TRACKING_USERNAME
    value: "admin"
  - name: MLFLOW_TRACKING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_ADMIN_PASSWORD

extraEnvFrom: |
  - secretRef:
      name: platform-secrets

# Webserver secret key
webserverSecretKeySecretName: my-webserver-secret

# Flower
flower:
  enabled: false

# # Redis (for CeleryExecutor)
# redis:
#   enabled: false

# Metrics
metrics:
  enabled: true
  statsd:
    enabled: true
    host: airflow-statsd
    port: 9125
    prefix: airflow
