executor: KubernetesExecutor

# Airflow environment
env:
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: /opt/airflow/dags
  - name: PYTHONPATH
    value: /opt/airflow/dags/repo
  - name: TEST_ENV
    value: "GOKULADETHYA"
  - name: AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE
    value: /opt/airflow/pod_templates/pod_template_file.yaml

# Extra environment from secrets
extraEnv: |
  - name: KAFKA_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: MLFLOW_TRACKING_URI
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_URI
  - name: MLFLOW_TRACKING_USERNAME
    value: "admin"
  - name: MLFLOW_TRACKING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_ADMIN_PASSWORD

extraEnvFrom: |
  - secretRef:
      name: platform-secrets

# Custom volumes for shared data
extraVolumes:
  - name: airflow-shared
    persistentVolumeClaim:
      claimName: shared-pvc-airflow
  - name: pod-template
    configMap:
      name: airflow-pod-template

extraVolumeMounts:
  - name: airflow-shared
    mountPath: /opt/airflow/custom_persistent_shared
  - name: pod-template
    mountPath: /opt/airflow/
    readOnly: true

webserverSecretKeySecretName: my-webserver-secret

# Custom Airflow image
airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest
  config:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: /opt/airflow/pod_templates/pod_template_file.yaml
  env:
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo

# DAGs configuration
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    wait: 10
  persistence:
    enabled: false  # disabled to avoid mount conflict

# Logs
logs:
  persistence:
    enabled: true
    existingClaim: shared-pvc

# Disable Flower
flower:
  enabled: false

# Redis disabled
redis:
  enabled: false

# Metrics
metrics:
  enabled: true
  statsd:
    enabled: true
    host: airflow-statsd
    port: 9125
    prefix: airflow
