executor: CeleryExecutor


airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest


dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    wait: 10
  persistence:
    enabled: true

