executor: CeleryExecutor  # or KubernetesExecutor

airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest
    pullPolicy: Always
  config:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags

# DAGs
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    wait: 10
  persistence:
    enabled: true
    existingClaim: shared-pvc-airflow
    accessMode: ReadWriteMany

# Extra environment variables
extraEnv: |
  - name: KAFKA_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: MLFLOW_TRACKING_URI
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_URI
  - name: MLFLOW_TRACKING_USERNAME
    value: "admin"
  - name: MLFLOW_TRACKING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_ADMIN_PASSWORD

extraEnvFrom: |
  - secretRef:
      name: platform-secrets

webserverSecretKeySecretName: my-webserver-secret
flower:
  enabled: false
# redis:
#   enabled: false

metrics:
  enabled: true
  statsd:
    enabled: true
    host: airflow-statsd
    port: 9125
    prefix: airflow
