# values.yaml - Dummy Airflow Helm chart values

executor: CeleryExecutor

# Airflow image settings
images:
  airflow:
    repository: apache/airflow
    tag: 3.7.0
    pullPolicy: IfNotPresent

# GitSync configuration for DAGs
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    rev: "HEAD"
    wait: 10
    depth: 1
    subPath: ""
    # optional: use SSH key instead of HTTPS token
    # sshKeySecret: "git-ssh-key"
    # knownHosts: |
    #   github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr...

persistence:
  enabled: true
  existingClaim: shared-airflow-pvc
  accessMode: ReadWriteMany
  size: 10Gi
  # optional: mount paths for Airflow
  mountPath: /opt/airflow/dags

logs:
  persistence:
    enabled: true
    existingClaim: shared-airflow-pvc
    accessMode: ReadWriteMany
    size: 10Gi
    mountPath: /opt/airflow/logs

# Celery Executor settings
celery:
  worker:
    replicas: 2
  flower:
    enabled: true

# Airflow configs
config:
  AIRFLOW__CORE__FERNET_KEY: "dummyfernetkey1234567890"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow@airflow-postgresql:5432/airflow"
  AIRFLOW__CELERY__BROKER_URL: "redis://airflow-redis:6379/0"

# PostgreSQL dependency (optional)
postgresql:
  enabled: true
  postgresqlDatabase: airflow
  postgresqlUsername: airflow
  postgresqlPassword: airflow

# Redis for Celery Broker
redis:
  enabled: true
