executor: CeleryExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 3.7.0
    pullPolicy: IfNotPresent

# DAG GitSync
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/example/airflow-dags.git"
    branch: "main"
    rev: "HEAD"
    wait: 30
    depth: 1
    subPath: ""

# DAGs persistence (shared PVC)
dags:
  persistence:
    enabled: true
    existingClaim: shared-airflow-pvc

# Logs persistence
logs:
  persistence:
    enabled: true
    existingClaim: shared-airflow-pvc

# Celery configuration
celery:
  worker:
    replicas: 2
  flower:
    enabled: true

# Airflow configs as key-value objects
config:
  AIRFLOW__CORE__FERNET_KEY:
    value: "dummyfernetkey1234567890"
  AIRFLOW__CORE__DAGS_FOLDER:
    value: "/opt/airflow/dags"
  AIRFLOW__CORE__EXECUTOR:
    value: "CeleryExecutor"
  AIRFLOW__CELERY__BROKER_URL:
    value: "redis://airflow-redis:6379/0"
  AIRFLOW__CELERY__RESULT_BACKEND:
    value: "db+postgresql://airflow:airflow@airflow-postgresql:5432/airflow"

# PostgreSQL (for Celery backend)
postgresql:
  enabled: true
  postgresqlDatabase: airflow
  postgresqlUsername: airflow
  postgresqlPassword: airflow

# Redis (for Celery broker)
redis:
  enabled: true
