executor: LocalExecutor

env:
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: /opt/airflow/dags/repo
  - name: PYTHONPATH
    value: /opt/airflow/dags/repo
  - name: TEST_ENV
    value: "GOKULADETHYA"

extraEnv: |
  - name: KAFKA_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: MLFLOW_TRACKING_URI
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_URI
  - name: MLFLOW_TRACKING_USERNAME
    value: "admin"
  - name: MLFLOW_TRACKING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: platform-secrets
        key: MLFLOW_ADMIN_PASSWORD

extraEnvFrom: |
  - secretRef:
      name: platform-secrets

webserverSecretKeySecretName: my-webserver-secret

airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest
  config:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/repo
  env:
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo

# DAGs
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    wait: 60
  persistence:
    enabled: true
    existingClaim: shared-pvc-airflow

# Optional: mount custom path safely using subPath
extraVolumes: |
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: shared-pvc-airflow

extraVolumeMounts: |
  - name: airflow-dags
    mountPath: /opt/airflow/custom_persistent_shared
    subPath: repo

flower:
  enabled: false

redis: 
  enabled: false

metrics:
  enabled: true
  statsd:
    enabled: true
    host: airflow-statsd
    port: 9125
    prefix: airflow
