executor: LocalExecutor

airflow:
  extraEnvFrom:
    - secretRef:
        name: platform-secrets
    - name: KAFKA_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/FrozenWolf-Cyber/crypto-mlops"
    branch: "master"
    subPath: "airflow"
    wait: 60
  persistence:
    enabled: true
    existingClaim: shared-pvc

flower:
  enabled: false


redis: 
  enabled: false

metrics:
  enabled: true
  statsd:
    enabled: true
    host: airflow-statsd
    port: 9125
    prefix: airflow



# ingress:
#   enabled: true
#   ingressClassName: nginx
#   hosts:
#     - airflow.gokuladethya.uk
#   tls:
#     - hosts:
#         - airflow.gokuladethya.uk
#       secretName: airflow-tls