executor: CeleryExecutor

airflow:
  image:
    repository: frozenwolf2003/mlops-airflow
    tag: latest


dags:
  persistence:
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteMany
    ## the name of an existing PVC to use
    existingClaim: shared-pvc-airflow
    subPath: ~
  gitSync:
    enabled: true
    repo: https://github.com/FrozenWolf-Cyber/crypto-mlops
    branch: master
    period: 5s
    wait: ~