controller:
  service:
    externalTrafficPolicy: Local
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    proxy-real-ip-cidr: |
      173.245.48.0/20,
      103.21.244.0/22,
      103.22.200.0/22,
      103.31.4.0/22,
      141.101.64.0/18,
      108.162.192.0/18,
      190.93.240.0/20,
      188.114.96.0/20,
      197.234.240.0/22,
      198.41.128.0/17,
      162.158.0.0/15,
      104.16.0.0/13,
      104.24.0.0/14,
      172.64.0.0/13,
      131.0.72.0/22

  # Optional: extra settings for stricter security
  service:
    annotations:
      # Prevent bypass via LoadBalancer by restricting only HTTPS/HTTP
      service.beta.kubernetes.io/hetzner-load-balancer-protocol: "https"
      service.beta.kubernetes.io/hetzner-load-balancer-uses-proxyprotocol: "true"

  # Enable access logs to debug whitelist behavior
  extraArgs:
    v: "2"

defaultBackend:
  enabled: true
