apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: platform
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 29092
      targetPort: 29092
  clusterIP: None  # headless service for direct pod DNS

---
# 2️⃣ Kafka Deployment (KRaft mode)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 29092  # broker
            - containerPort: 29093  # controller
            - containerPort: 9092   # external
            - containerPort: 9101   # JMX
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_JMX_HOSTNAME
              value: "localhost"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@broker:29093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
            - name: CLUSTER_ID
              value: "NDY5ZDJlOTYtM2QxYi00Nm" # replace with your generated UUID
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "24"

          volumeMounts:
            - name: shared
              mountPath: /tmp/kraft-combined-logs  # Kafka logs folder
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-pvc  # reuse existing PVC

---
# 3️⃣ Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: platform
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093
    - name: external
      port: 9092
      targetPort: 9092
---
# 4️⃣ Schema Registry Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"

      #     volumeMounts:
      #       - name: shared
      #         mountPath: /etc/schema-registry

      # volumes:
      #   - name: shared
      #     persistentVolumeClaim:
      #       claimName: shared-pvc  # reuse existing PVC


---
# 5️⃣ Schema Registry Service
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: platform
spec:
  selector:
    app: schema-registry
  ports:
    - port: 8081
      targetPort: 8081
---
# 6️⃣ Control Center Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: control-center
          image: confluentinc/cp-enterprise-control-center:7.5.0
          ports:
            - containerPort: 9021
          env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER
              value: "connect:8083"
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: "1"
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: "1"
            - name: PORT
              value: "9021"
---
# 7️⃣ Control Center Service
apiVersion: v1
kind: Service
metadata:
  name: control-center
  namespace: platform
spec:
  selector:
    app: control-center
  ports:
    - port: 9021
      targetPort: 9021
---
# 8️⃣ REST Proxy Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-proxy
  template:
    metadata:
      labels:
        app: rest-proxy
    spec:
      containers:
        - name: rest-proxy
          image: confluentinc/cp-kafka-rest:7.5.0
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_REST_HOST_NAME
              value: "rest-proxy"
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8082"
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
---
# 9️⃣ REST Proxy Service
apiVersion: v1
kind: Service
metadata:
  name: rest-proxy
  namespace: platform
spec:
  selector:
    app: rest-proxy
  ports:
    - port: 8082
      targetPort: 8082
