apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'mlflow'
        static_configs:
          - targets: ['mlflow.platform.svc:5000']
      # Add training pods later when available
      - job_name: 'k8s-internal'
        static_configs:
          - targets: []

# ===============================
# Prometheus Deployment & Service
# ===============================
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.47.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: platform
spec:
  type: NodePort 
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 9090